### ISSUE TITLE
Completar los microservicios con UPDATE

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#12]
Añadir a las API REST creadas un método UPDATE que actualice algún dato en el servidos, mínimo uno por cada microservicio.

Buscar la documentación necesaria para poder realizar esta tarea.

**Comment by AlbertFX91** [comment]
Finalizado el UPDATE de Premios 6ad36d85015e8ad560bef20e3d17ca737200bbf3

**Comment by mirromsan** [comment]
Añadido el UPDATE a Rutas

**Comment by juagarfer4** [comment]
Añadido el UPDATE a Historial

**Comment by Fasgort** [comment]
Añadido el UPDATE a Logros

**Comment by rubtavpic** [comment]
Añadido el UPDATE a Entrenamientos

**Comment by mirromsan** [comment]
Revisión UPDATE de @AlbertFX91  @rubtavpic 
- UPDATE se hace correctamente en POSTMAN

Revisión pasada

**Comment by AlbertFX91** [comment]
Revisión UPDATE de @Fasgort @mirromsan y @juagarfer4 
- [x] Update de logros
- [x] Update de rutas
- [x] Update de historial

**Comment by AlbertFX91** [comment]
Todos los microservicios llevan incorporados los UPDATE
