### ISSUE TITLE
Añadir objetos de Entrenamiento a la base de datos

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#20]
Se deben añadir los objetos correspondientes a la API REST de Trainings con los datos modificados. Estos datos se encuentran en la carpeta Fit&Grow > SI > Modelos > Conceptual model.pdf

El tiempo estimado de esta tarea es de 30 minutos.

**Comment by mirromsan** [comment]
Revisión:
- Objetos nuevos del modelo añadido correctamente
- CRUD se hace correctamente en POSTMAN

Revisión pasada
