### ISSUE TITLE
Añadir objetos de Historial a la base de datos

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#21]
Se deben añadir los objetos correspondientes a la API REST de Records con los datos modificados. Estos datos se encuentran en la carpeta Fit&Grow > SI > Modelos > Conceptual model.pdf

El tiempo estimado de esta tarea es de 10 minutos.

**Comment by mirromsan** [comment]
Revisión:
- Falta añadir totalTime
- Cambiar el botón atrás a inglés

**Comment by juagarfer4** [comment]
Añadido totalTime a Records

**Comment by mirromsan** [comment]
Revisión:
- Añadido totalTime a la API Records
