### ISSUE TITLE
Listar los objetos de la historia de usuario Logros

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#29]
(MODIFICADO POR ALBERTO)
- Modificar los datos de Logros para adaptarse al modelo conceptual (Para el tema de herencia usa un atributo string que se llame 'type' que sea igual a uno de los tres tipos de los hijos, de esa forma diferenciamos si es un hijo u otro)
- Modificar la API Logros para que use BD
- Listar todos los logros del sistema sin tener el cuenta el progreso

El tiempo estimado de esta tarea es de 120 minutos.

**Comment by Fasgort** [comment]
Resuelto en "API de logros adaptada para el uso de DB" #42
