### ISSUE TITLE
Paquete Usuario

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#47]
Esta tarea se ha creado para realizar todo el tratamiento y desarrollo referente al registro, logueo, sesión y API REST de Usuario.

La primera parte de la tarea que debe realizarse, es la búsqueda e investigación sobre el uso de Auth0 dentro del ámbito del sistema multiusuario y autenticación en el frontend, y su integración dentro del proyecto Fit&Grow.

El siguiente paso a realizar dentro de esta tarea será crear la base de datos correspondiente y empleando el modelo visto en la reunión previa para implementar la clase Usuario.

Otro de los pasos posteriores a la búsqueda de información y al desarrollo de la funcionalidad de registro de usuario, es el desarrollo de la funcionalidad y el diseño referente al inicio de sesión del usuario.

Por último, se debe desarrollar y diseñar toda la API REST para que trabaje con la autenticación del usuario, así como reajustar el frontend teniendo en cuenta toda la funcionalidad  diseñada en esta tarea.

Todo trabajo debe estar documentado a modo de manual con todo lo referente a ésta tarea, para que el resto de componentes del equipo sepa, llegado el momento, atacar el problema y solucionarlo.

**Comment by AlbertFX91** [comment]
Diseñado la API REST para nueva colección de usuarios, así como autenticación

**Comment by AlbertFX91** [comment]
Diseñado servicio frontend para encapsulación de funcionalidad de autenticación

**Comment by AlbertFX91** [comment]
Desarrollado login funcional
