### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#48]
Se debe investigar el uso de la herramienta swagger para la creación de la documentación y testeo de la aplicación web Fit&Grow. Para ello se dispone del video realizado por el profesor en clase, además de toda la documentación al respecto que el encargado de esta tarea pueda encontrar en Internet.

Una vez hecha la tarea previa de invesigación, el trabajo consistirá en realizar el esqueleto de la documentación en swagger para poder ir integrando cada parte de desarrollo dentro de la documentación. La ruta de acceso a la documentación del proyecto será **/docs**.

Todo trabajo debe estar documentado a modo de manual con todo lo referente a ésta tarea, para que el resto de componentes del equipo sepa, llegado el momento, atacar el problema y solucionarlo.

**Comment by juagarfer4** [comment]
Como se recoge en la documentación, además de modificar el archivo server.js, se han instalado los siguientes módulos:

npm install -g swagger

npm install swagger-tools --save

npm instal swagger-express-mw --save
