### ISSUE TITLE
API REST Entrenamiento y computo de horas Toggl

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#5]
Se debe hacer una API REST de gestión CRUD (Sin contar con el método UPDATE) que den un soporte parcial a la historia de usuario del entrenamiento desplegado en local.

Además se debe mantener en todo momento el control del tiempo de realización de la tarea, así como el tiempo de búsqueda de documentación y de tareas relacionadas con el proyecto Fit&Grow.

**Comment by mirromsan** [comment]
Revisión:
- Falta GET que devuelva un solo entrenamiento

**Comment by rubtavpic** [comment]
Arreglado la parte del GET que devuelva un entrenamiento solo

**Comment by mirromsan** [comment]
Revisión:
- Código comentado correctamente
- CRUD se hace correctamente en POSTMAN

Revisión pasada
