### ISSUE TITLE
Logro completado

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#54]
La tarea consistirá en añadir una columna mas en el frontend que indique que se ha conseguido el logro o por el contrario que no se ha conseguido.

**Comment by Fasgort** [comment]
Solucionado en #57.

En lugar de en una columna, el icono del logro pasa a estar en color cuando se ha conseguido el logro, mientras que permanece en blanco y negro cuando está pendiente.

Aparte, se separan los logros conseguidos (que aparecen en primer lugar), y a continuación, separados, los logros sin conseguir.

**Comment by juagarfer4** [comment]
Una vez comprobada la diferenciación entre logros completados y por completar, se da por cerrada la issue.
