### ISSUE TITLE
Visibilidad de logros

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#55]
La tarea consiste en diseñar el frontend de tal manera que los logros que falten sean visibles a la hora de empezar el entrenamiento y cuando termine éste se muestren los logros que se han conseguido.

En el frontend se deben ver los logros a punto de conseguir justo cuando vamos a comenzar un entrenamiento. Además de verse los logros que se han conseguido después de realizar el entrenamiento y el progreso del usuario.

Todo trabajo debe estar documentado a modo de manual con todo lo referente a ésta tarea, para que el resto de componentes del equipo sepa, llegado el momento, atacar el problema y solucionarlo.

**Comment by Fasgort** [comment]
La funcionalidad para visualizar los logros a punto de conseguir, ya existe en el commit 72b9a99e01a6e0b723702fc18de82dd629702ed0.

**Comment by Fasgort** [comment]
Solucionado en #60

**Comment by juagarfer4** [comment]
Una vez comprobado el progreso en los logros, se da la issue por cerrada.
