### ISSUE TITLE
API REST Histórico y computo de horas Toggl

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#6]
Se debe hacer una API REST de gestión CRUD (Sin contar con el método UPDATE) que den un soporte parcial a la historia de usuario del histórico desplegado en local.

Además se debe mantener en todo momento el control del tiempo de realización de la tarea, así como el tiempo de búsqueda de documentación y de tareas relacionadas con el proyecto Fit&Grow.

**Comment by juagarfer4** [comment]
Realizados los métodos GET, POST, PUT y DELETE para Historial, a falta de revisión

**Comment by AlbertFX91** [comment]
Revisión satisfactoria
