### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#63]
Se deben modificar las clases, los atributos y las consultas en función del modelo que hemos visto en la reunión para que todas las consultas y la funcionalidad quede bien determinada para mostrar si hay algún error en cualquiera de las consultas y dejarlo todo listo para integrarlo en heroku.

**Comment by mirromsan** [comment]
postman completado en local a falta de heroku. Se deja en progreso a la espera de si se añaden nuevos métodos.
