### ISSUE TITLE
Objetos de prueba para las APIs

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#66]
En todas las APIs se deben crear tres datos de prueba, es decir, tres objetos que se creen en la base de datos nada mas crear la tabla correspondiente.

Cada objeto de prueba contará con un atributo id cuyos valores deben ser numéricos y deben ser correlativos (Ej: ..., 4, 5, 6, ...)

**Comment by mirromsan** [comment]
Se han creado nuevos métodos get con idUsuario.
