### ISSUE TITLE
API REST Premios y computo de horas Toggl

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#7]
Se debe hacer una API REST de gestión CRUD (Sin contar con el método UPDATE) que den un soporte parcial a la historia de usuario de premios desplegado en local.

Además se debe mantener en todo momento el control del tiempo de realización de la tarea, así como el tiempo de búsqueda de documentación y de tareas relacionadas con el proyecto Fit&Grow.

**Comment by AlbertFX91** [comment]
Realizado las operaciones CR_D para los premios

**Comment by mirromsan** [comment]
Revisión:
- Código comentado correctamente
- CRUD se hace correctamente en POSTMAN

Revisión pasada
