### ISSUE TITLE
Frontend y registro de usuario

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#70]
En esta tarea se debe desarrollar toda la parte del registro de usuario y la parte de frontend dedicada a esta funcionalidad.

Se debe crear también la parte del frontend de la página principal de Fit&Grow.

**Comment by AlbertFX91** [comment]
A continuación te indico los errores que he visto:
- postman.html hacerlo por las rutas de angularjs, de forma que así reutilizamos footer y header
- Eliminar el boton de home en el postman.html ya que si hacemos lo indicado arriba, tendremos acceso al home
- Registro: Las fechas me deja indicar la que quiera sin importar el formato (Usar input date o validacion html5 a traves de expresiones regulares)
- Registro: Errata en el boton de enviar. Pone 'sing in' 😛 
- Registro: En los campos numéricos me deja introducir tanto letras como valores negativos 

Por lo demas todo bien!

**Comment by mirromsan** [comment]
Creo que ya está todo corregido, echarle un ojito y unirlo a dev si está bien
