### ISSUE TITLE
API REST Logros y computo de horas Toggl

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#8]
Se debe hacer una API REST de gestión CRUD (Sin contar con el método UPDATE) que den un soporte parcial a la historia de usuario de los logros desplegado en local.

Además se debe mantener en todo momento el control del tiempo de realización de la tarea, así como el tiempo de búsqueda de documentación y de tareas relacionadas con el proyecto Fit&Grow.

**Comment by Fasgort** [comment]
He basado el código en prizes.js. Si hay algún error con prizes.js, notificadmelo porque entonces achievements.js lo tendrá también.

**Comment by AlbertFX91** [comment]
abdcad1be4ecef75edf0ba024743ddc97b3dd1b5 El fichero server.js no puede estar en la carpeta routes. Debemos eliminar ese fichero y los cambios que hayas realizado incluirlos en el fichero server.js en la raiz

**Comment by AlbertFX91** [comment]
Revisión satisfactoria
