### ISSUE TITLE
API REST Rutas y computo de horas Toggl

### ISSUE THREAD

**Issue by rubtavpic** [AlbertFX91/fitngrow#9]
Se debe hacer una API REST de gestión CRUD (Sin contar con el método UPDATE) que den un soporte parcial a la historia de usuario de rutas desplegado en local.

Además se debe mantener en todo momento el control del tiempo de realización de la tarea, así como el tiempo de búsqueda de documentación y de tareas relacionadas con el proyecto Fit&Grow.

**Comment by mirromsan** [comment]
Finalizada la API REST Rutas y el computo de horas a falta de revisión

**Comment by AlbertFX91** [comment]
Revisión satisfactoria
